# Housing Rental Analysis for San Francisco

In this challenge, your job is to use your data visualization skills, including aggregation, interactive visualizations, and geospatial analysis, to find properties in the San Francisco market that are viable investment opportunities.

## Instructions

Use the `san_francisco_housing.ipynb` notebook to visualize and analyze the real-estate data.

Note that this assignment requires you to create a visualization by using hvPlot and GeoViews. Additionally, you need to read the `sfo_neighborhoods_census_data.csv` file from the `Resources` folder into the notebook and create the DataFrame that you’ll use in the analysis.

The main task in this Challenge is to visualize and analyze the real-estate data in your Jupyter notebook. Use the `san_francisco_housing.ipynb` notebook to complete the following tasks:

* Calculate and plot the housing units per year.

* Calculate and plot the average prices per square foot.

* Compare the average prices by neighborhood.

* Build an interactive neighborhood map.

* Compose your data story.

### Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualization.

4. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting bar chart.](Images/zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analyzing?

### Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?

### Compare the Average Sale Prices by Neighborhood

For this part of the assignment, use interactive visualizations and widgets to explore the average sale price per square foot by neighborhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/pricing-info-by-neighborhood.png)

6. Use the interactive visualization to answer the following question:

    * For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

### Build an Interactive Neighborhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualizations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighborhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. The second cell cleans the data and sets the “Neighborhood” column. Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualization.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

    * Set the `geo` parameter to True.
    * Set the `size` parameter to “sale_price_sqr_foot”.
    * Set the `color` parameter to “gross_rent”.
    * Set the `frame_width` parameter to 700.
    * Set the `frame_height` parameter to 500.
    * Include a descriptive title.

Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

### Compose Your Data Story

Based on the visualizations that you created, answer the following questions:

* How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

* What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

In [27]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Import the data 

In [28]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
sfo_data_df = pd.read_csv(Path('../San_Francisco_Housing_Market_Analysis/Resources/sfo_neighborhoods_census_data.csv')).drop_duplicates().dropna()

# Review the first and last five rows of the DataFrame
display(sfo_data_df.head())
display(sfo_data_df.tail())

year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

year            neighborhood  sale_price_sqr_foot  housing_units  \
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
392        4390  
393        4390  
394        4390  
395        4390  
396        4390

In [29]:
np.round(sfo_data_df['sale_price_sqr_foot'], decimals = 3)

0      291.183
1      267.933
2      170.099
3      347.395
4      319.028
        ...   
392    903.050
393    970.085
394    552.603
395    328.319
396    631.195
Name: sale_price_sqr_foot, Length: 392, dtype: float64

---

## Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualization.

4. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting bar chart.](Images/zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analyzing?



### Step 1: Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

In [30]:
# Create a new variable called housing units by year and slice out the year and housing unit columns from sfo DataFrame
housing_units_by_year = sfo_data_df[["year", "housing_units"]]

display(housing_units_by_year.head())
display(housing_units_by_year.tail())

year  housing_units
0  2010         372560
1  2010         372560
2  2010         372560
3  2010         372560
4  2010         372560

year  housing_units
392  2016         384242
393  2016         384242
394  2016         384242
395  2016         384242
396  2016         384242

In [31]:
# Create a numerical aggregation that groups the number of housing units by the year and then averages the results.
housing_units_by_year.groupby('year').housing_units.mean()



year
2010    372560.0
2011    374507.0
2012    376454.0
2013    378401.0
2014    380348.0
2015    382295.0
2016    384242.0
Name: housing_units, dtype: float64

### Step 2: Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

### Step 3: Style and format the line plot to ensure a professionally styled visualization.

In [32]:
# Import NumericalTickFormatter to add commas to x & y axis'
from bokeh.models.formatters import NumeralTickFormatter

formatter = NumeralTickFormatter(format='0,0')


# Create a visual aggregation explore the housing units by year
housing_units_by_year.hvplot.bar(
    x = "year",
    y = "housing_units",
    xlabel = "Year", 
    ylabel = "Housing Units",
    ylim = (340000, 395000),
    frame_width=600,
    frame_height=300,
    yformatter = '%.0f',
    title = "Housing Units in San Fransico from 2010-2016",
).opts(
    yformatter = formatter
)



:Bars   [year]   (housing_units)

### Step 5: Answer the following question:

**Question:** What is the overall trend in housing_units over the period being analyzed?

**Answer:** The overall trend from 2010-2016 is a nice, steady and small progression in the average number of housing units available in San Fransisco. Each year the average number of units increased by exactly 1,947 new units available. Could be a sign of more construction in the city, increasing the total number of units, or can also be a sign of a steady outflow of residents moving out of San Fransisco.

---

## Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?



### Step 1: Group the data by year, and then average the results.

In [33]:
# Create a new DataFrame called prices square foot by year and slice out the 
# Needed columns from sfo DataFrame
sfo_data_by_year = sfo_data_df.groupby('year')[['sale_price_sqr_foot', 'housing_units', 'gross_rent']].mean()


display(sfo_data_by_year)



sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

**Question:** What is the lowest gross rent reported for the years included in the DataFrame?

**Answer:** # YOUR ANSWER HERE

### Step 2: Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

In [34]:
# Filter out the housing_units column, creating a new DataFrame 
# Keep only sale_price_sqr_foot and gross_rent averages per year
prices_square_foot_by_year = sfo_data_by_year[['sale_price_sqr_foot', 'gross_rent']] 

# Review the DataFrame
display(prices_square_foot_by_year)

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

### Step 3: Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

> **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`

### Step 4: Style and format the line plot to ensure a professionally styled visualization.


In [35]:
prices_square_foot_by_year_plot = prices_square_foot_by_year.hvplot(
    label = 'Sale Price Per Square Foot and Average Gross Rent | San Francisco 2010-2016',
    xlabel = "Year", 
    ylabel = "Gross Rent/Sale Price Per Square Foot")

prices_square_foot_by_year_plot

:NdOverlay   [Variable]
   :Curve   [year]   (value)

### Step 6: Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

**Question:** Did any year experience a drop in the average sale price per square foot compared to the previous year?

**Answer:** Yes, in 2011 the average sale price per square foot fell to $341.90 in from the previous year's average of $369.34 per square foot. All other years in dataframe have an increase from year prior.

**Question:** If so, did the gross rent increase or decrease during that year?

**Answer:** Unfortunately, in 2011 when the average sale price per square foot declined, the gross rent still increased from $1,239 to $1,530. Although the rate of increase was lower than other years.

---

## Compare the Average Sale Prices by Neighborhood

For this part of the assignment, use interactive visualizations and widgets to explore the average sale price per square foot by neighborhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/pricing-info-by-neighborhood.png)

6. Use the interactive visualization to answer the following question:

    * For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 


### Step 1: Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

In [36]:
# Group by year and neighborhood and then create a new dataframe of the mean values
prices_by_year_by_neighborhood = sfo_data_df.groupby(['year', 'neighborhood']).mean()

# Review the DataFrame
display(prices_by_year_by_neighborhood.head())
display(prices_by_year_by_neighborhood.tail())

sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                    
2010 Alamo Square               291.182945       372560.0      1239.0
     Anza Vista                 267.932583       372560.0      1239.0
     Bayview                    170.098665       372560.0      1239.0
     Buena Vista Park           347.394919       372560.0      1239.0
     Central Richmond           319.027623       372560.0      1239.0

sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                          
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

### Step 2: Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [37]:
# Filter out the housing_units
prices_by_year_by_neighborhood = prices_by_year_by_neighborhood.drop(columns='housing_units')

# Review the first and last five rows of the DataFrame
display(prices_by_year_by_neighborhood.head())
display(prices_by_year_by_neighborhood.tail())

sale_price_sqr_foot  gross_rent
year neighborhood                                     
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

sale_price_sqr_foot  gross_rent
year neighborhood                                           
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

### Step 3: Create an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

### Step 4: Style and format the line plot to ensure a professionally styled visualization.

In [38]:
# Use hvplot to create an interactive line plot of the average price per square foot
# The plot should have a dropdown selector for the neighborhood
prices_by_year_by_neighborhood_plot = prices_by_year_by_neighborhood.hvplot(
    groupby = 'neighborhood',
    title = 'Sale Price Per Square Foot and Average Gross Rent By Neighborhood | San Francisco 2010-2016',
    x = 'year',
    xlabel = "Year", 
    ylabel = "Gross Rent/Sale Price Per Square Foot"
    
)

prices_by_year_by_neighborhood_plot

BokehModel(combine_events=True, render_bundle={'docs_json': {'e8d04115-658e-42f6-a343-ebb91463705b': {'version…

### Step 6: Use the interactive visualization to answer the following question:

**Question:** For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

**Answer:** The average sale price per square foot it significantly less in 2016 than what it was in 2012. Falling from $344.491 per square foot in 2012, all the way down to $88.402 in 2016. Contrary to the over-all trend in San Fransico, the Anza Vista neighborhood at a smaller scale is showing lower sale prices per yer since 2014.

---

## Build an Interactive Neighborhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualizations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighborhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. The second cell cleans the data and sets the “Neighborhood” column. Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualization.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `size_max` parameter to “25”.

    * Set the `zoom` parameter to “11”.

Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?


### Step 1: Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

In [39]:
# Load neighborhoods coordinates data
neighborhood_locations_df = pd.read_csv(
    Path('../San_Francisco_Housing_Market_Analysis/Resources/neighborhoods_coordinates.csv'),
    index_col='Neighborhood')

neighborhood_locations_df.drop_duplicates()
neighborhood_locations_df.dropna()

# Review the DataFrame
display(neighborhood_locations_df.head())
display(neighborhood_locations_df.tail())

Lat         Lon
Neighborhood                          
Alamo Square     37.791012 -122.402100
Anza Vista       37.779598 -122.443451
Bayview          37.734670 -122.401060
Bayview Heights  37.728740 -122.410980
Bernal Heights   37.728630 -122.443050

Lat         Lon
Neighborhood                            
West Portal         37.74026 -122.463880
Western Addition    37.79298 -122.435790
Westwood Highlands  37.73470 -122.456854
Westwood Park       37.73415 -122.457000
Yerba Buena         37.79298 -122.396360

### Step 2: Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

In [40]:
# Calculate the mean values for each neighborhood
all_neighborhood_info_df = sfo_data_df.groupby('neighborhood').mean()

# Review the resulting DataFrame
display(all_neighborhood_info_df.head())
display(all_neighborhood_info_df.tail())

year  sale_price_sqr_foot  housing_units   gross_rent
neighborhood                                                                 
Alamo Square     2013.000000           366.020712       378401.0  2817.285714
Anza Vista       2013.333333           373.382198       379050.0  3031.833333
Bayview          2012.000000           204.588623       376454.0  2318.400000
Bayview Heights  2015.000000           590.792839       382295.0  3739.000000
Bernal Heights   2013.500000           576.746488       379374.5  3080.333333

year  sale_price_sqr_foot  housing_units   gross_rent
neighborhood                                                                
West Portal         2012.25           498.488485      376940.75  2515.500000
Western Addition    2012.50           307.562201      377427.50  2555.166667
Westwood Highlands  2012.00           533.703935      376454.00  2250.500000
Westwood Park       2015.00           687.087575      382295.00  3959.000000
Yerba Buena         2012.50           576.709848      377427.50  2555.166667

In [41]:
all_neighborhood_info_df = all_neighborhood_info_df[['sale_price_sqr_foot', 'gross_rent']]

display(all_neighborhood_info_df.head())
display(all_neighborhood_info_df.tail())

sale_price_sqr_foot   gross_rent
neighborhood                                     
Alamo Square              366.020712  2817.285714
Anza Vista                373.382198  3031.833333
Bayview                   204.588623  2318.400000
Bayview Heights           590.792839  3739.000000
Bernal Heights            576.746488  3080.333333

sale_price_sqr_foot   gross_rent
neighborhood                                        
West Portal                  498.488485  2515.500000
Western Addition             307.562201  2555.166667
Westwood Highlands           533.703935  2250.500000
Westwood Park                687.087575  3959.000000
Yerba Buena                  576.709848  2555.166667

In [42]:
all_neighborhood_info_df = np.round(all_neighborhood_info_df[['sale_price_sqr_foot', 'gross_rent']], decimals = 2
    )

display(all_neighborhood_info_df)

sale_price_sqr_foot  gross_rent
neighborhood                                       
Alamo Square                     366.02     2817.29
Anza Vista                       373.38     3031.83
Bayview                          204.59     2318.40
Bayview Heights                  590.79     3739.00
Bernal Heights                   576.75     3080.33
...                                 ...         ...
West Portal                      498.49     2515.50
Western Addition                 307.56     2555.17
Westwood Highlands               533.70     2250.50
Westwood Park                    687.09     3959.00
Yerba Buena                      576.71     2555.17

[73 rows x 2 columns]

### Step 3: Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. 

Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. 

The second cell cleans the data and sets the “Neighborhood” column. 

Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualization.

In [43]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())


Lat         Lon  sale_price_sqr_foot  gross_rent
Alamo Square     37.791012 -122.402100               366.02     2817.29
Anza Vista       37.779598 -122.443451               373.38     3031.83
Bayview          37.734670 -122.401060               204.59     2318.40
Bayview Heights  37.728740 -122.410980               590.79     3739.00
Bernal Heights   37.728630 -122.443050                  NaN         NaN

Lat        Lon  sale_price_sqr_foot  gross_rent
Yerba Buena      37.79298 -122.39636               576.71     2555.17
Bernal Heights        NaN        NaN               576.75     3080.33
Downtown              NaN        NaN               391.43     2817.29
Ingleside             NaN        NaN               367.90     2509.00
Outer Richmond        NaN        NaN               473.90     2817.29

In [44]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_df = all_neighborhoods_df.reset_index().dropna()

# Rename the "index" column as "Neighborhood" for use in the Visualization
all_neighborhoods_df = all_neighborhoods_df.rename(columns={"index": "Neighborhood"})

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

Neighborhood        Lat         Lon  sale_price_sqr_foot  gross_rent
0      Alamo Square  37.791012 -122.402100               366.02     2817.29
1        Anza Vista  37.779598 -122.443451               373.38     3031.83
2           Bayview  37.734670 -122.401060               204.59     2318.40
3   Bayview Heights  37.728740 -122.410980               590.79     3739.00
5  Buena Vista Park  37.768160 -122.439330               452.68     2698.83

Neighborhood       Lat         Lon  sale_price_sqr_foot  gross_rent
68         West Portal  37.74026 -122.463880               498.49     2515.50
69    Western Addition  37.79298 -122.435790               307.56     2555.17
70  Westwood Highlands  37.73470 -122.456854               533.70     2250.50
71       Westwood Park  37.73415 -122.457000               687.09     3959.00
72         Yerba Buena  37.79298 -122.396360               576.71     2555.17

In [45]:
all_neighborhoods_df.head(72)

Neighborhood        Lat         Lon  sale_price_sqr_foot  gross_rent
0         Alamo Square  37.791012 -122.402100               366.02     2817.29
1           Anza Vista  37.779598 -122.443451               373.38     3031.83
2              Bayview  37.734670 -122.401060               204.59     2318.40
3      Bayview Heights  37.728740 -122.410980               590.79     3739.00
5     Buena Vista Park  37.768160 -122.439330               452.68     2698.83
..                 ...        ...         ...                  ...         ...
68         West Portal  37.740260 -122.463880               498.49     2515.50
69    Western Addition  37.792980 -122.435790               307.56     2555.17
70  Westwood Highlands  37.734700 -122.456854               533.70     2250.50
71       Westwood Park  37.734150 -122.457000               687.09     3959.00
72         Yerba Buena  37.792980 -122.396360               576.71     2555.17

[69 rows x 5 columns]

In [46]:
all_neighborhoods_df.sort_values(by='sale_price_sqr_foot')

Neighborhood       Lat        Lon  sale_price_sqr_foot  \
59         Silver Terrace  37.73467 -122.40106               170.29   
24          Hunters Point  37.72551 -122.37178               170.62   
2                 Bayview  37.73467 -122.40106               204.59   
47          Outer Mission  37.72280 -122.43869               242.37   
67      Visitacion Valley  37.72874 -122.41098               301.47   
..                    ...       ...        ...                  ...   
71          Westwood Park  37.73415 -122.45700               687.09   
51        Pacific Heights  37.79298 -122.43579               689.56   
38          Miraloma Park  37.73415 -122.45700               779.81   
36         Merced Heights  37.71993 -122.46595               788.84   
65  Union Square District  37.79101 -122.40210               903.99   

    gross_rent  
59     3528.00  
24     1239.00  
2      2318.40  
47     2995.75  
67     3657.00  
..         ...  
71     3959.00  
51     2817.29  
38     2155.25  
36     3414.00  
65     2555.17  

[69 rows x 5 columns]

In [47]:
all_neighborhoods_df.sort_values(by='gross_rent')

Neighborhood       Lat        Lon  sale_price_sqr_foot  gross_rent
24      Hunters Point  37.72551 -122.37178               170.62     1239.00
19      Forest Knolls  37.75706 -122.45509               321.84     1781.50
12    Diamond Heights  37.72863 -122.44305               434.99     2016.00
60        South Beach  37.78323 -122.40065               650.12     2099.00
38      Miraloma Park  37.73415 -122.45700               779.81     2155.25
..                ...       ...        ...                  ...         ...
36     Merced Heights  37.71993 -122.46595               788.84     3414.00
59     Silver Terrace  37.73467 -122.40106               170.29     3528.00
67  Visitacion Valley  37.72874 -122.41098               301.47     3657.00
3     Bayview Heights  37.72874 -122.41098               590.79     3739.00
71      Westwood Park  37.73415 -122.45700               687.09     3959.00

[69 rows x 5 columns]

In [48]:
all_neighborhoods_df.max()

Neighborhood           Yerba Buena
Lat                       37.80152
Lon                     -122.37178
sale_price_sqr_foot         903.99
gross_rent                  3959.0
dtype: object

### Step 4: Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

* Set the `geo` parameter to True.
* Set the `size` parameter to “sale_price_sqr_foot”.
* Set the `color` parameter to “gross_rent”.
* Set the `frame_width` parameter to 700.
* Set the `frame_height` parameter to 500.
* Include a descriptive title.

In [49]:
# Create a plot to analyze neighborhood info
map_plot = all_neighborhoods_df.hvplot.points(
    'Lon',
    'Lat', 
    geo=True,
    size='sale_price_sqr_foot',
    color='gross_rent',
    hover_cols='all',
    hover_color='orange',
    alpha=0.5,
    tiles='OSM',
    frame_width=700,
    frame_height=500,
    title='Sale Price/Square Foot and Gross Rent for San Francisco Neighborhoods'
    
)

map_plot

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot,index,Neighborhood)

### Step 5: Use the interactive map to answer the following question:

**Question:** Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

**Answer:** Westwood Park has the highest gross rent at $3,959 per month, while Union Square District has the higest sale price per square foot at $903.990 per square foot.

## Compose Your Data Story

Based on the visualizations that you have created, compose a data story that synthesizes your analysis by answering the following questions:

**Question:**  How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

**Answer:** While both rental income and sales price per square foot have been increasing, the rental income growth as been at a much higher rate than the growth sales price. One reason behind this is that not every neighborhood has an increasing sales price as some neighborhoods have been decreasing or staying stagnant in sales price, which lowres the average of the entire city. The same cannot be said about rental income as every neighborhood has increasing rental income. 

**Question:** What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

**Answer:** I would suggest for my compnay to focus on areas with declining, stagnant or very low growth so that our compnay can capitalize on any potential growth to come in the future. Another thing I would consider would be, if we were looking to hold the assets and adding rental income to our portfolio, focusing on areas with average to lower areas of rental income growth so that we may also benefit from opportunities to increasing rental growth rates by investing into the asset. Based on the interactive map above we would want to focus on points that are smaller than average, while also have some transparency and less color than the others. That being said, based on the data available, I would suggest that our compnay focus on the Northwest side of the town and East side of town. Specifically, the neighborhood's of Anza Vista, Lone Mountain, Lake -- The Presidio & Inner Richmond on the Northwest side of town and Inner Mission & Mission Dolores on the East side of town. 